version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - samplenet

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      APP_PORT: 8000
      DB_DIALECT: postgresql
      DB_DRIVER: org.postgresql.Driver
    networks:
      - samplenet
volumes:
  postgres-data:

networks:
  samplenet: