server:
  port: ${APP_PORT}
  servlet:
    context-path: /api
spring:
  application:
    name: damovie
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_DATABASE}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: ${DB_DIALECT}
